// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        (unknown)
// source: pymon/pymon.proto

package pymon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PymonCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PymonId       string                 `protobuf:"bytes,1,opt,name=pymon_id,json=pymonId,proto3" json:"pymon_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RepositoryId  string                 `protobuf:"bytes,3,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Exp           int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Status        *Status                `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Skill1        int32                  `protobuf:"varint,7,opt,name=skill1,proto3" json:"skill1,omitempty"`
	Skill2        int32                  `protobuf:"varint,8,opt,name=skill2,proto3" json:"skill2,omitempty"`
	Skill3        int32                  `protobuf:"varint,9,opt,name=skill3,proto3" json:"skill3,omitempty"`
	Skill4        int32                  `protobuf:"varint,10,opt,name=skill4,proto3" json:"skill4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonCreated) Reset() {
	*x = PymonCreated{}
	mi := &file_pymon_pymon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonCreated) ProtoMessage() {}

func (x *PymonCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonCreated.ProtoReflect.Descriptor instead.
func (*PymonCreated) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{0}
}

func (x *PymonCreated) GetPymonId() string {
	if x != nil {
		return x.PymonId
	}
	return ""
}

func (x *PymonCreated) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *PymonCreated) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *PymonCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PymonCreated) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PymonCreated) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PymonCreated) GetSkill1() int32 {
	if x != nil {
		return x.Skill1
	}
	return 0
}

func (x *PymonCreated) GetSkill2() int32 {
	if x != nil {
		return x.Skill2
	}
	return 0
}

func (x *PymonCreated) GetSkill3() int32 {
	if x != nil {
		return x.Skill3
	}
	return 0
}

func (x *PymonCreated) GetSkill4() int32 {
	if x != nil {
		return x.Skill4
	}
	return 0
}

type PymonNameChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PymonId       string                 `protobuf:"bytes,1,opt,name=pymon_id,json=pymonId,proto3" json:"pymon_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonNameChanged) Reset() {
	*x = PymonNameChanged{}
	mi := &file_pymon_pymon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonNameChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonNameChanged) ProtoMessage() {}

func (x *PymonNameChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonNameChanged.ProtoReflect.Descriptor instead.
func (*PymonNameChanged) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{1}
}

func (x *PymonNameChanged) GetPymonId() string {
	if x != nil {
		return x.PymonId
	}
	return ""
}

func (x *PymonNameChanged) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PymonExpChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PymonId       string                 `protobuf:"bytes,1,opt,name=pymon_id,json=pymonId,proto3" json:"pymon_id,omitempty"`
	Exp           int64                  `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonExpChanged) Reset() {
	*x = PymonExpChanged{}
	mi := &file_pymon_pymon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonExpChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonExpChanged) ProtoMessage() {}

func (x *PymonExpChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonExpChanged.ProtoReflect.Descriptor instead.
func (*PymonExpChanged) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{2}
}

func (x *PymonExpChanged) GetPymonId() string {
	if x != nil {
		return x.PymonId
	}
	return ""
}

func (x *PymonExpChanged) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// Duplicate message definition.
type PymonStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PymonId       string                 `protobuf:"bytes,1,opt,name=pymon_id,json=pymonId,proto3" json:"pymon_id,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonStatusChanged) Reset() {
	*x = PymonStatusChanged{}
	mi := &file_pymon_pymon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonStatusChanged) ProtoMessage() {}

func (x *PymonStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonStatusChanged.ProtoReflect.Descriptor instead.
func (*PymonStatusChanged) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{3}
}

func (x *PymonStatusChanged) GetPymonId() string {
	if x != nil {
		return x.PymonId
	}
	return ""
}

func (x *PymonStatusChanged) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// Duplicate message definition.
type PymonSkillChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PymonId       string                 `protobuf:"bytes,1,opt,name=pymon_id,json=pymonId,proto3" json:"pymon_id,omitempty"`
	Skill1        int32                  `protobuf:"varint,2,opt,name=skill1,proto3" json:"skill1,omitempty"`
	Skill2        int32                  `protobuf:"varint,3,opt,name=skill2,proto3" json:"skill2,omitempty"`
	Skill3        int32                  `protobuf:"varint,4,opt,name=skill3,proto3" json:"skill3,omitempty"`
	Skill4        int32                  `protobuf:"varint,5,opt,name=skill4,proto3" json:"skill4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonSkillChanged) Reset() {
	*x = PymonSkillChanged{}
	mi := &file_pymon_pymon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonSkillChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonSkillChanged) ProtoMessage() {}

func (x *PymonSkillChanged) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonSkillChanged.ProtoReflect.Descriptor instead.
func (*PymonSkillChanged) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{4}
}

func (x *PymonSkillChanged) GetPymonId() string {
	if x != nil {
		return x.PymonId
	}
	return ""
}

func (x *PymonSkillChanged) GetSkill1() int32 {
	if x != nil {
		return x.Skill1
	}
	return 0
}

func (x *PymonSkillChanged) GetSkill2() int32 {
	if x != nil {
		return x.Skill2
	}
	return 0
}

func (x *PymonSkillChanged) GetSkill3() int32 {
	if x != nil {
		return x.Skill3
	}
	return 0
}

func (x *PymonSkillChanged) GetSkill4() int32 {
	if x != nil {
		return x.Skill4
	}
	return 0
}

type PymonDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PymonDeleted) Reset() {
	*x = PymonDeleted{}
	mi := &file_pymon_pymon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PymonDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PymonDeleted) ProtoMessage() {}

func (x *PymonDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_pymon_pymon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PymonDeleted.ProtoReflect.Descriptor instead.
func (*PymonDeleted) Descriptor() ([]byte, []int) {
	return file_pymon_pymon_proto_rawDescGZIP(), []int{5}
}

func (x *PymonDeleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pymon_pymon_proto protoreflect.FileDescriptor

var file_pymon_pymon_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x79, 0x6d, 0x6f, 0x6e,
	0x1a, 0x14, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x0c, 0x50, 0x79, 0x6d, 0x6f, 0x6e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x79, 0x6d, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x79, 0x6d, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x79, 0x6d, 0x6f, 0x6e,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x31, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x31,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x32, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x32, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x33, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x33,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x34, 0x22, 0x41, 0x0a, 0x10, 0x50, 0x79, 0x6d, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0f, 0x50,
	0x79, 0x6d, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x5f, 0x0a, 0x12, 0x50,
	0x79, 0x6d, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x79, 0x6d, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x8e, 0x01, 0x0a,
	0x11, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x32, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x33, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x33, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x34, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x34, 0x22, 0x1e, 0x0a,
	0x0c, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0xa4, 0x01,
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x79, 0x6d, 0x6f,
	0x6e, 0x42, 0x0a, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x2d, 0x4b, 0x69,
	0x7a, 0x75, 0x6b, 0x75, 0x2f, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x70, 0x79, 0x6d, 0x6f, 0x6e, 0xa2, 0x02, 0x03, 0x50, 0x50, 0x58, 0xaa,
	0x02, 0x0b, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0xca, 0x02, 0x0b,
	0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x5c, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0xe2, 0x02, 0x17, 0x50, 0x79,
	0x6d, 0x6f, 0x6e, 0x5c, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x50, 0x79, 0x6d, 0x6f, 0x6e, 0x3a, 0x3a, 0x50,
	0x79, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pymon_pymon_proto_rawDescOnce sync.Once
	file_pymon_pymon_proto_rawDescData = file_pymon_pymon_proto_rawDesc
)

func file_pymon_pymon_proto_rawDescGZIP() []byte {
	file_pymon_pymon_proto_rawDescOnce.Do(func() {
		file_pymon_pymon_proto_rawDescData = protoimpl.X.CompressGZIP(file_pymon_pymon_proto_rawDescData)
	})
	return file_pymon_pymon_proto_rawDescData
}

var file_pymon_pymon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pymon_pymon_proto_goTypes = []any{
	(*PymonCreated)(nil),       // 0: pymon.pymon.PymonCreated
	(*PymonNameChanged)(nil),   // 1: pymon.pymon.PymonNameChanged
	(*PymonExpChanged)(nil),    // 2: pymon.pymon.PymonExpChanged
	(*PymonStatusChanged)(nil), // 3: pymon.pymon.PymonStatusChanged
	(*PymonSkillChanged)(nil),  // 4: pymon.pymon.PymonSkillChanged
	(*PymonDeleted)(nil),       // 5: pymon.pymon.PymonDeleted
	(*Status)(nil),             // 6: pymon.resource.Status
}
var file_pymon_pymon_proto_depIdxs = []int32{
	6, // 0: pymon.pymon.PymonCreated.status:type_name -> pymon.resource.Status
	6, // 1: pymon.pymon.PymonStatusChanged.status:type_name -> pymon.resource.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pymon_pymon_proto_init() }
func file_pymon_pymon_proto_init() {
	if File_pymon_pymon_proto != nil {
		return
	}
	file_pymon_resource_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pymon_pymon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pymon_pymon_proto_goTypes,
		DependencyIndexes: file_pymon_pymon_proto_depIdxs,
		MessageInfos:      file_pymon_pymon_proto_msgTypes,
	}.Build()
	File_pymon_pymon_proto = out.File
	file_pymon_pymon_proto_rawDesc = nil
	file_pymon_pymon_proto_goTypes = nil
	file_pymon_pymon_proto_depIdxs = nil
}
