services:
  server:
    build:
      context: server
    volumes:
      - ./:/src/pymon-graphql
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    volumes:
      - pymon-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pymon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 30s
      timeout: 5s
      retries: 6
      start_period: 30s
  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
volumes:
  pymon-data:
