CREATE TABLE `pythons_skills` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `pp` INT UNSIGNED NOT NULL DEFAULT 0,
  `attack` INT UNSIGNED NOT NULL DEFAULT 0,
  `hit_rate` INT UNSIGNED NOT NULL DEFAULT 0,
  `min_version` VARCHAR(10) NOT NULL DEFAULT '0.0.0',
  `max_version` VARCHAR(10) NOT NULL DEFAULT '9.9.9',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
