// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PythonSkill struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Pp          int32  `json:"pp"`
	Attack      int32  `json:"attack"`
	HitRate     int32  `json:"hitRate"`
	MinVersion  string `json:"minVersion"`
	MaxVersion  string `json:"maxVersion"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
