// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PythonSkill struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Pp          int    `json:"pp"`
	Attack      int    `json:"attack"`
	HitRate     int    `json:"hitRate"`
	MinVersion  string `json:"minVersion"`
	MaxVersion  string `json:"maxVersion"`
}

type Query struct {
}

type Subscription struct {
}

type Time struct {
	UnixTime  int    `json:"unixTime"`
	TimeStamp string `json:"timeStamp"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
