package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.62

import (
	"context"
	"fmt"

	"github.com/K-Kizuku/pymon-graphql/pkg/graph/model"
)

// User is the resolver for the user field.
func (r *pythonResolver) User(ctx context.Context, obj *model.Python) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Stats is the resolver for the stats field.
func (r *pythonResolver) Stats(ctx context.Context, obj *model.Python) (*model.PythonStats, error) {
	panic(fmt.Errorf("not implemented: Stats - stats"))
}

// Skills is the resolver for the skills field.
func (r *pythonStatsResolver) Skills(ctx context.Context, obj *model.PythonStats) ([]*model.PythonSkill, error) {
	panic(fmt.Errorf("not implemented: Skills - skills"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Python is the resolver for the python field.
func (r *queryResolver) Python(ctx context.Context) (*model.Python, error) {
	panic(fmt.Errorf("not implemented: Python - python"))
}

// Python returns PythonResolver implementation.
func (r *Resolver) Python() PythonResolver { return &pythonResolver{r} }

// PythonStats returns PythonStatsResolver implementation.
func (r *Resolver) PythonStats() PythonStatsResolver { return &pythonStatsResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type pythonResolver struct{ *Resolver }
type pythonStatsResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *pythonResolver) Skills(ctx context.Context, obj *model.Python) ([]*model.PythonSkill, error) {
	panic(fmt.Errorf("not implemented: Skills - skills"))
}
*/
